### ISSUE TITLE
Move the "Dem" logo up on about page

### ISSUE THREAD

**Issue by progcodepreston** [mjabraham47/dnc-election#2]
On the [About page](https://rundnc.herokuapp.com/#!/about) - The Dem logo should be more centered instead of bleeding over onto the blue underneath.

![image](https://cloud.githubusercontent.com/assets/24799748/22616471/3cf2bff2-ea73-11e6-9b73-3486495ec75a.png)

**Comment by KamillaKhabibrakhmanova** [comment]
Closing, since we ended up doing a complete redesign of the about page :)
